### ISSUE TITLE
Guide?

### ISSUE THREAD

**Issue by Robthekilla** [OBNinjaa/queue-waiter#1]
How do we connect to the proxy, no video on your youtube

**Comment by OBNinjaa** [comment]
Pretty straight forward install your dependencies **(npm install)** then fill out your username in **src/username.json** 
Then start it with **node .** or **node src/proxy.js**
You may also get a message asking you to link your Microsoft account at **[microsoft.com](https://microsoft.com/link)** and then enter a code to authenticate which you can get from looking at your console **(You only need to do this once)**
